name: morningstar_library
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  tailwind_colors: ^0.3.1
  loader_overlay: ^2.3.2
  flutter_modular: ^6.3.2
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  image_picker: ^1.0.4
  image_cropper: ^5.0.0
  reactive_forms: ^16.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-Black.ttf
          weight: 900
    - family: Wildy
      fonts:
        - asset: assets/fonts/Wildy-Sans-Regular.ttf
    - family: Fall In Love
      fonts:
        - asset: assets/fonts/Fall-In-Love.ttf
    - family: JustAnotherHand
      fonts:
        - asset: assets/fonts/JustAnotherHand-Regular.ttf
    - family: Mauline
      fonts:
        - asset: assets/fonts/Mauline.otf
